// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSGCTf74EI9CtPUesGLywjRsolFyPiV64',
    appId: '1:989294463998:web:695bd55548e01b9a75ceaf',
    messagingSenderId: '989294463998',
    projectId: 'exkool-3e2f0',
    authDomain: 'exkool-3e2f0.firebaseapp.com',
    storageBucket: 'exkool-3e2f0.appspot.com',
    measurementId: 'G-YH30D328WN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIzXmCOYQovnS7aRyfUPwaMc4lxpb8rLI',
    appId: '1:989294463998:android:916146c5d34eb5c175ceaf',
    messagingSenderId: '989294463998',
    projectId: 'exkool-3e2f0',
    storageBucket: 'exkool-3e2f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnbV8qB5GHakFEwYQ7jb2tCNVO-Chypa0',
    appId: '1:989294463998:ios:cb0884e06bc69abf75ceaf',
    messagingSenderId: '989294463998',
    projectId: 'exkool-3e2f0',
    storageBucket: 'exkool-3e2f0.appspot.com',
    iosClientId: '989294463998-e2cg5ejrrv6tl296e90ii3hsl1afcqk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ekskul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnbV8qB5GHakFEwYQ7jb2tCNVO-Chypa0',
    appId: '1:989294463998:ios:cb0884e06bc69abf75ceaf',
    messagingSenderId: '989294463998',
    projectId: 'exkool-3e2f0',
    storageBucket: 'exkool-3e2f0.appspot.com',
    iosClientId: '989294463998-e2cg5ejrrv6tl296e90ii3hsl1afcqk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.ekskul',
  );
}
